
# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
knx: !include knx.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob:
    # 修改所有小爱的对话实体
    "sensor.xiaomi_*_conversation":
      interval_seconds: 3 # 默认5秒
