alias: 小爱对话自动化之主卧
description: 关键词匹配和小爱对话内容并操作对应的设备
mode: single
triggers:
  - entity_id: sensor.xiaomi_s12_e74f_conversation
    trigger: state
conditions:
  - condition: template
    value_template: |
      {{ (trigger.to_state|default(0)) and as_timestamp(now()) -
      as_timestamp(trigger.to_state.attributes.timestamp) < 60 }}
      {# 限制60秒内的对话 #}
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ '打开主灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_main_light
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭主灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_main_light
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开射灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bed_headlight
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭射灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bed_headlight
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开床尾灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bed_headlight
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭床尾灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bed_headlight
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开床头灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bedside_lamp
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭床头灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_bedside_lamp
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开灯带' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_light_strip
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭灯带' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_light_strip
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开衣帽间灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_entrance_spotlight
            data: {}
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭衣帽间灯' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: light.master_bedroom_entrance_spotlight
            data: {}
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '打开纱帘' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_gauze_curtain
            data: {}
            action: switch.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭纱帘' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_gauze_curtain
            data: {}
            action: switch.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '打开窗纱' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_gauze_curtain
            data: {}
            action: switch.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭窗纱' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_gauze_curtain
            data: {}
            action: switch.turn_on
      - conditions:
          - condition: template
            value_template: |
              {{ '打开布帘' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_curtains
            data: {}
            action: switch.turn_off
      - conditions:
          - condition: template
            value_template: |
              {{ '关闭布帘' in trigger.to_state.state }}
        sequence:
          - target:
              entity_id: switch.master_bedroom_curtains
            data: {}
            action: switch.turn_on
      - conditions:
          - condition: template
            value_template: "{{ '准备睡觉' in trigger.to_state.state }}"
        sequence:
          - data: {}
            target:
              entity_id: scene.zhu_wo_yu_shui_jue
            action: scene.turn_on
      - conditions:
          - condition: template
            value_template: "{{ '晚安' in trigger.to_state.state }}"
        sequence:
          - data: {}
            target:
              entity_id: scene.shui_jue
            action: scene.turn_on
      - conditions:
          - condition: template
            value_template: "{{ '起床' in trigger.to_state.state }}"
        sequence:
          - data: {}
            target:
              entity_id: scene.zhu_wo_qi_chuang
            action: scene.turn_on
      - conditions:
          - condition: template
            value_template: "{{ '准备起床' in trigger.to_state.state }}"
        sequence:
          - data: {}
            target:
              entity_id: scene.zhu_wo_yu_qi_chuang
            action: scene.turn_on
      - conditions:
          - condition: template
            value_template: "{{ '主卧观影' in trigger.to_state.state }}"
        sequence:
          - metadata: {}
            target:
              entity_id: scene.zhu_wo_guan_ying
            action: scene.turn_on
            data: {}
      - conditions:
          - condition: template
            value_template: "{{ '结束观影' in trigger.to_state.state }}"
        sequence:
          - metadata: {}
            target:
              entity_id: scene.jie_shu_zhu_wo_guan_ying
            action: scene.turn_on
            data: {}
    default: []
  - data:
      level: info
      logger: custom_components.xiaomi_miot.xiaoai
      message: |
        {{ trigger.entity_id }}: {{ trigger.to_state.state }}
    action: system_log.write
