alias: 小爱对话自动化之玄关
description: 关键词匹配和小爱对话内容并操作对应的设备
trigger:
  - platform: state
    entity_id: sensor.xiaomi_l05c_0bb3_conversation
condition:
  - condition: template
    value_template: |
      {{ (trigger.to_state|default(0)) and as_timestamp(now()) -
      as_timestamp(trigger.to_state.attributes.timestamp) < 60 }}
      {# 限制60秒内的对话 #}
action:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ '离家模式' in trigger.to_state.state }}
        sequence:
          - service: sence.turn_on
            target:
              entity_id: scene.chi_jia_zhong_zhi
            data: {}

    default: []
  - service: system_log.write
    data:
      level: info
      logger: custom_components.xiaomi_miot.xiaoai
      message: |
        {{ trigger.entity_id }}: {{ trigger.to_state.state }}
mode: single
