alias: 日落窗帘自动化
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.master_bedroom_curtains
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.restaurant_gauze_curtain
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.living_room_gauze_curtain
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.children_s_room_gauze_curtain
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.gauze_curtain_for_elders_room
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.master_bedroom_gauze_curtain
mode: single
