alias: 玄关人体感应器回家模式
description: 检查家里没有开灯且厨房光照低于50开启回家模式
trigger:
  - platform: state
    entity_id:
      - sensor.xiaomi_lx06_b297_conversation
condition:
  - condition: template
    value_template: |
      {{ (trigger.to_state|default(0)) and as_timestamp(now()) -
      as_timestamp(trigger.to_state.attributes.timestamp) < 60 }}
      {# 限制60秒内的对话 #}
  - condition: state
    entity_id: light.restaurant_chandelier
    state: "off"
  - condition: state
    entity_id: light.restaurant_spotlights
    state: "off"
  - condition: state
    entity_id: light.living_room_center_spotlight
    state: "off"
  - condition: state
    entity_id: light.living_room_downlight
    state: "off"
  - condition: state
    entity_id: light.living_room_ceiling_light_strip
    state: "off"
  - condition: state
    entity_id: light.tv_background_light_strip
    state: "off"
  - condition: state
    entity_id: light.living_room_main_light
    state: "off"
  - condition: template
    value_template: "{{ '玄关人体感应器自动化回家' in trigger.to_state.state }}"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.hui_jia
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.zai_jia_mo_shi
    metadata: {}
mode: single
